/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment1;

import java.awt.HeadlessException;
import java.sql.*;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
// import java.util.Date;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author senju
 */
public class dashb extends javax.swing.JFrame {

    /**
     * Creates new form dashb
     */
    String imgpath;
    Connection conn;
    DefaultTableModel model;
    int id;

    public dashb() {
        initComponents();
        model = (DefaultTableModel) table.getModel();
        conn = UserDbs2.getConnection();
        UserDbs2.createInfoTable();
        //displayToTable();  //retrieving the from dbs;
        //showDataInTable();   //retrieving the from dbs and store it to vector
        showDataInTable2();

    }

    private void displayToTable() {

        try {
            model.setRowCount(0);
            String query = "SELECT * FROM Info ORDER BY Id asc";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                int id = rs.getInt("Id");
                String img = rs.getString("ImgPath");
                String name = rs.getString("Name");
                int age = rs.getInt("Age");
                String course = rs.getString("Course");
                String date = rs.getString("Date");
                model.addRow(new Object[]{id, img, name, age, course, date});
            }

        } catch (SQLException e) {

        }
    }

    private void showDataInTable() {
        int rowCount = 0;
        try {
            String query = "SELECT * FROM Info";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            //ResultSetMetaData rmd = rs.getMetaData();
            //int colCount = rmd.getColumnCount();
            model.setRowCount(0);

            while (rs.next()) {
                Vector v1 = new Vector();
                Collections.addAll(v1, rs.getInt("Id"), rs.getString("ImgPath"), rs.getString("Name"), rs.getInt("Age"),
                        rs.getString("Course"), rs.getDate("Date"));
                model.addRow(v1);
                rowCount++;
            }
        } catch (SQLException e) {
        }
    }

    private void showDataInTable2() {

        ArrayList<userInfo> data = new ArrayList<>();
        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM Info";
            ResultSet rs = stmt.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();

            int colCount = rsmd.getColumnCount();
            userInfo info;

            while (rs.next()) {
                info = new userInfo(rs.getInt("Id"), rs.getString("ImgPath"), rs.getString("Name"), rs.getInt("Age"),
                        rs.getString("Course"), rs.getDate("Date"));
                data.add(info);
            }
            Object[] row = new Object[colCount];
            model.setRowCount(0);

            for (userInfo datalist : data) {
                row[0] = datalist.getId();
                row[1] = datalist.getImg();
                row[2] = datalist.getName();
                row[3] = datalist.getAge();
                row[4] = datalist.getCourse();
                row[5] = datalist.getDate();
                model.addRow(row);

            }

        } catch (SQLException e) {
        }
    }

    public void clear() {
        dateChooser.setDate(null);
        imgholder.setIcon(null);
        displayID.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        imgholder = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayID = new javax.swing.JTextArea();
        nameTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        fc.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dash Board");
        setPreferredSize(new java.awt.Dimension(720, 517));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 517));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Log-out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        imgholder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 110));

        jButton2.setText("Upload Img");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 2);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, 40));

        dateChooser.setBackground(new java.awt.Color(255, 255, 255));
        dateChooser.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Image Path", "Name", "Age", "Course", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 670, 230));

        displayID.setEditable(false);
        displayID.setBackground(new java.awt.Color(255, 255, 255));
        displayID.setColumns(20);
        displayID.setLineWrap(true);
        displayID.setTabSize(0);
        displayID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        displayID.setEnabled(false);
        displayID.setMinimumSize(new java.awt.Dimension(82, 22));
        displayID.setPreferredSize(new java.awt.Dimension(82, 22));
        jScrollPane1.setViewportView(displayID);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, -1));
        jPanel1.add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 170, -1));
        jPanel1.add(ageTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 70, -1));

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 83, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Course:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Age:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Message", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            LoginForm login = new LoginForm();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
        fc.setCurrentDirectory(new File("C:\\Users\\senju\\Documents\\NetBeansProjects\\EDP\\src\\Img"));
        fc.addChoosableFileFilter(filter);

        int rslt = fc.showOpenDialog(jPanel1);
        if (rslt == JFileChooser.APPROVE_OPTION) {
            File selectedfile = fc.getSelectedFile();
            imgpath = selectedfile.getAbsolutePath();
            ImageIcon newImage = new ImageIcon(imgpath);
            Image image = newImage.getImage();
            Image myImage = image.getScaledInstance(imgholder.getWidth(), imgholder.getHeight(), Image.SCALE_SMOOTH);
            newImage = new ImageIcon(myImage);
            imgholder.setIcon(newImage);
            System.out.println("Image Uploaded");
        } else {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        id = 10000 + random.nextInt(90000);
        String name = nameTf.getText();
        String course = cb.getSelectedItem().toString();
        String strgAge = ageTf.getText();
        int age = Integer.parseInt(strgAge);
        Date date = Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(dateChooser.getDate()));

        //database
        try {
            //Adding the data to database
            PreparedStatement ps = conn.prepareStatement("INSERT INTO Info(Id, ImgPath, Name, Age, Course, Date)VALUES(?,?,?,?,?,?)");
            ps.setInt(1, id);
            ps.setString(2, imgpath);
            ps.setString(3, name);
            ps.setInt(4, age);
            ps.setString(5, course);
            ps.setDate(6, date);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success", "Successfully Added", JOptionPane.INFORMATION_MESSAGE);
            clear();

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(this, "Invalid Input", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        //
        model.addRow(new Object[]{id, imgpath, name, age, course, date});


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String date = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();
        PreparedStatement ps;

        int row = table.getSelectedRow();
        id = (int) model.getValueAt(row, 0); // Assuming ID is an integer
        String strID = String.valueOf(id);

        try {
            ps = conn.prepareStatement("UPDATE Info SET ImgPath = ?, Date = ? WHERE Id = ?");

            ps.setString(1, imgpath);
            ps.setString(2, date);
            ps.setInt(3, id);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(dashb.class.getName()).log(Level.SEVERE, null, ex);
        }

        model.setValueAt(strID, row, 0);
        model.setValueAt(imgpath, row, 1);
        model.setValueAt(date, row, 2);
        clear();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
/*
        int row = table.getSelectedRow();

        id = (int) model.getValueAt(row, 0);
        String strID = String.valueOf(id);

        imgpath = model.getValueAt(row, 1).toString();
        ImageIcon newImage = new ImageIcon(imgpath);
        Image image = newImage.getImage();
        Image myImage = image.getScaledInstance(imgholder.getWidth(), imgholder.getHeight(), Image.SCALE_SMOOTH);
        newImage = new ImageIcon(myImage);

        //dispaly
        imgholder.setIcon(newImage);
        displayID.setText(strID);

        try {
            dt = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(row, 2));
            dateChooser.setDate(dt);
        } catch (ParseException ex) {
            Logger.getLogger(dashb.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
        int row = table.getSelectedRow();
        id = (int) model.getValueAt(row, 0);
        String query = "SELECT * FROM Info WHERE Id = '" + id + "'";
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String strgId = String.valueOf(rs.getInt("Id"));
                imgpath = rs.getString("ImgPath");
                String name = rs.getString("Name");
                String age = String.valueOf(rs.getInt("Age"));
                String course = rs.getString("Course");
                ImageIcon newImage = new ImageIcon(imgpath);
                Image image = newImage.getImage();
                Image myImage = image.getScaledInstance(imgholder.getWidth(), imgholder.getHeight(), Image.SCALE_SMOOTH);
                newImage = new ImageIcon(myImage);

                displayID.setText(strgId);
                imgholder.setIcon(newImage);
                nameTf.setText(name);
                ageTf.setText(age);
                cb.setSelectedItem(course);
                dateChooser.setDate(rs.getDate("Date"));

            }
        } catch (SQLException e) {

        }

    }//GEN-LAST:event_tableMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        try {
            int row = table.getSelectedRow();
            int message = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Message", JOptionPane.YES_NO_OPTION);

            if (message == 0) {
                ps = conn.prepareStatement("DELETE FROM Info WHERE Id = ?");

                ps.setInt(1, id);

                ps.executeUpdate();
                model.removeRow(row);
                JOptionPane.showMessageDialog(null, "Deleted Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                clear();
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashb.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTf;
    private javax.swing.JComboBox<String> cb;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea displayID;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel imgholder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
