/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment1;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author senju
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    private final UserData userdata;

    Connection conn;

    public RegistrationForm() {
        userdata = new UserData();
        initComponents();
        conn = databaseConn.getConnection();
        databaseConn.createUsersTable();
    }

    public void clear() {
        username.setText(null);
        password.setText(null);
        cpassword.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(390, 350));

        jPanel1.setBackground(new java.awt.Color(55, 61, 58));
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 302));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 330));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 141, 116));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 237));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-user-26.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 74, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-lock-26.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 124, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-lock-26.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 174, 30, -1));

        username.setBackground(new java.awt.Color(255, 250, 237));
        username.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        username.setToolTipText("");
        username.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 270, 35));

        password.setBackground(new java.awt.Color(255, 250, 237));
        password.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 270, 35));

        cpassword.setBackground(new java.awt.Color(255, 250, 237));
        cpassword.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        cpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, 35));

        jButton1.setBackground(new java.awt.Color(231, 155, 97));
        jButton1.setText("Sign-up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 270, 30));

        jLabel5.setForeground(new java.awt.Color(255, 250, 237));
        jLabel5.setText("Already have an account?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 155, 97));
        jLabel6.setText("Login here");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        LoginForm login = new LoginForm();
        login.show();
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname = username.getText();
        String pass = new String(password.getPassword());
        String cpass = new String(cpassword.getPassword());

        if (uname.isEmpty() || pass.isEmpty() || cpass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields is require to fill", "Message", JOptionPane.INFORMATION_MESSAGE);
        } else if (userdata.isUserExists(uname)) {
            JOptionPane.showMessageDialog(null, "USER IS ALREADY EXIST", "message", JOptionPane.WARNING_MESSAGE);
            clear();
        } else if (pass.equals(cpass)) {
            if (password.getPassword().length <= 7) {
                JOptionPane.showMessageDialog(null, "Password must be at least 8 characters", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
               // userdata.addUser(uname, pass);
                try {

                    PreparedStatement ps = conn.prepareStatement("INSERT INTO Users(Username, Password)VALUES(?,?)");
                    ps.setString(1, uname);
                    ps.setString(2, pass);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Success", "Successfully Registered", JOptionPane.INFORMATION_MESSAGE);
                    clear();
                    
                } catch (Exception e) {
                    System.out.println(e);
                    //JOptionPane.showMessageDialog(this, "Invalid Input", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (password != cpassword) {
            JOptionPane.showMessageDialog(null, "Password and Confirm Password didn't match", "Error", JOptionPane.ERROR_MESSAGE);
            clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JPasswordField password;
    protected javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
