/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment1;

/**
 *
 * @author senju
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingbar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingbar.setBackground(new java.awt.Color(102, 102, 102));
        loadingbar.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, 10));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 30, -1));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loading...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/marie-lena-maslofski-loadingscreen-bg-3-ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SplashScreen().setVisible(true);
//            }
//        });
        SplashScreen splash = new SplashScreen();
        splash.setVisible(true);

        for (int i = 0; i <= 100; i++) {

            Thread.sleep(80);
            splash.jLabel2.setText(i + "%");

//            if(i == 10){
//                splash.jLabel1.setText("Initializing... Please hold on..");
//            } else if (i == 20){
//                splash.jLabel1.setText("Gathering resources... Almost there!");
//            } else if (i == 30){
//                splash.jLabel1.setText("Connecting the dots... Patience is key!");
//            }else if (i == 40){
//                splash.jLabel1.setText("Loading data... Just a moment...");
//            }else if (i == 50){
//                splash.jLabel1.setText("Setting things up... We're getting closer!");
//            }else if (i == 60){
//                splash.jLabel1.setText("Crunching numbers... Hang tight!");
//            }else if (i == 70){
//                splash.jLabel1.setText("Configuring settings... We're almost ready!");
//            }else if (i == 80){
//                splash.jLabel1.setText("Almost there... Stay with us!");
//            }else if (i == 90){
//                splash.jLabel1.setText("Finishing touches... Almost done!");
//            }else if (i == 97){
//                splash.jLabel1.setText("Loading complete!");
//            }
            switch (i) {
                case 10 ->
                    splash.jLabel1.setText("Initializing... Please hold on..");
                case 20 ->
                    splash.jLabel1.setText("Gathering resources... Almost there!");
                case 30 ->
                    splash.jLabel1.setText("Connecting the dots... Patience is key!");
                case 40 ->
                    splash.jLabel1.setText("Loading data... Just a moment...");
                case 50 ->
                    splash.jLabel1.setText("Setting things up... We're getting closer!");
                case 60 ->
                    splash.jLabel1.setText("Crunching numbers... Hang tight!");
                case 70 ->
                    splash.jLabel1.setText("Configuring settings... We're almost ready!");
                case 80 ->
                    splash.jLabel1.setText("Almost there... Stay with us!");
                case 90 ->
                    splash.jLabel1.setText("Finishing touches... Almost done!");
                case 97 ->
                    splash.jLabel1.setText("Loading complete!");
                default -> {
                }
            }

            splash.loadingbar.setValue(i);
        }
        LoginForm login = new LoginForm();
        login.setVisible(true);
        splash.setVisible(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar loadingbar;
    // End of variables declaration//GEN-END:variables
}
